FROM maven:3.9.6-eclipse-temurin-21 AS build

WORKDIR /app

COPY mvnw mvnw.cmd pom.xml ./
COPY .mvn/ .mvn/
COPY src/ src/

RUN chmod +x mvnw \
    && ./mvnw clean package -DskipTests -B

#layer 2    
FROM eclipse-temurin:21-jre AS runtime

RUN useradd --create-home --shell /bin/bash appuser

WORKDIR /home/appuser/app

COPY --from=build /app/target/*.jar ./app.jar

RUN chown -R appuser:appuser /home/appuser/app

USER appuser


ENTRYPOINT ["java", "-jar", "app.jar"]